[package]
name = "bench_helper"
version = "0.1.0"
authors = ["Greg Bowyer <gbowyer@fastmail.co.uk>"]
edition = "2018"

[features]
default = []
perf_stats = ["perfcnt"]

[dependencies]
criterion = "0.3"
stats_alloc = "0.1.8"
perfcnt = { version = "0.6", optional = true }
